modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="fast_jim"
description='''
Mekanism chemical and gas-port integration for Stardust Industry.
'''

[[dependencies.${mod_id}]]
    modId="stardustindustry"
    type="required"
    versionRange="[${mod_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanism"
    type="required"
    versionRange="[10.7.19,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
